media:
  input: public/images
  output: /images

content:
  - name: posts
    label: Posts
    path: content/post
    type: collection
    format: yaml-frontmatter
    view:
      fields: [title, published, image]
      primary: title
      sort: [published]
      default:
        search: ""
        sort: published
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: published
        label: Published Date
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
      - name: draft
        label: Draft
        type: boolean
        required: false
        default: false
      - name: category
        label: Category
        type: string
        required: false
      - name: tags
        label: Tags
        type: string
        list: true
        required: false
      - name: instagramEmbed
        label: Instagram Post Embed
        type: string
        required: false
      - name: imagesDownloadUrl
        label: Images Download URL
        type: string
        required: false
      - name: image
        label: Cover Image
        type: image
        required: false
        options:
          input: public/images
          output: /images
      - name: carousel
        label: Carousel
        type: image
        list: true
        required: false
        options:
          input: public/images
          output: /images
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: about
    icon: info
    label: About Page
    path: src/content/page/about.md
    type: file

  - name: config
    label: Site Config
    icon: bolt
    path: src/data/config.json
    type: file
    format: json
    fields:
      - name: title
        label: Site Title
        type: string
        required: true
      - name: description
        label: Site Description
        type: string
        required: true
      - name: tagLine
        label: Tag Line
        type: string
        required: true
      - name: defaultOgImage
        label: Default Open Graph Image
        type: string
        default: "./og.jpg"
      - name: latestPosts
        label: Latest Posts
        type: number
        default: 3
        options:
          min: 1
          max: 10
      - name: postsPerPage
        label: Posts Per Page
        type: number
        default: 10
        options:
          min: 1
          max: 20
      - name: socials
        label: Socials
        required: true
        type: object
        fields:
          - name: _
            default: _
            hidden: true
          - name: discord
            label: Discord
            type: string
          - name: facebook
            label: Facebook
            type: string
          - name: github
            label: GitHub
            type: string
          - name: instagram
            label: Instagram
            type: string
          - name: linkedin
            label: LinkedIn
            type: string
          - name: linktree
            label: Linktree
            type: string
          - name: twitter
            label: Twitter
            type: string
          - name: whatsapp
            label: WhatsApp
            type: string
          - name: youtube
            label: YouTube
            type: string

  - name: members
    label: Members
    type: collection
    icon: users
    format: json
    path: content/member
    filename: "{fields.role}_{fields.name}.json"
    view:
      fields: [role, name, course, sem, image]
      primary: name
      sort: [role, name]
      default:
        search: ""
        sort: role
        order: asc
    fields:
      - name: role
        label: Role
        type: select
        options:
          values:
            [
              president,
              vice-president,
              secretary,
              joint-secretary,
              treasurer,
              media-liaison,
              head-flagger,
              flagger,
            ]
        required: true
      - name: name
        label: Name
        type: string
        required: true
      - name: course
        label: Course
        type: string
        required: true
      - name: sem
        label: Semester
        type: number
        required: true
        options:
          min: 1
          max: 10
      - name: image
        label: Image
        type: image
        options:
          input: public/images/members
          output: /images/members
        default: /images/members/default.png
        required: true
      - name: socials
        label: Socials
        type: object
        required: true
        fields:
          - name: _
            default: _
            hidden: true
          - name: website
            label: website
            type: string
          - name: discord
            label: Discord
            type: string
          - name: facebook
            label: Facebook
            type: string
          - name: github
            label: GitHub
            type: string
          - name: instagram
            label: Instagram
            type: string
          - name: linkedin
            label: LinkedIn
            type: string
          - name: linktree
            label: Linktree
            type: string
          - name: twitter
            label: Twitter
            type: string
          - name: whatsapp
            label: WhatsApp
            type: string
          - name: youtube
            label: YouTube
            type: string
